# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.2
FROM python:3.10-alpine

# set workdir
WORKDIR /app

# install dependencies
COPY requirements.txt ./
RUN apk add --no-cache build-base libffi-dev openssl-dev musl-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del build-base musl-dev libffi-dev openssl-dev

# copy source
COPY . /app

# inform python to use UTF-8
ENV PYTHONUNBUFFERED=1

# default env defaults
ENV METASO_API_KEY=""

# start server
CMD ["python", "server.py"]
